global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kundereg"
    metrics_path: /metrics
    static_configs:
      - targets: ["kundereg:9464"]
        labels:
          service: kundereg

  - job_name: "foererkort"
    metrics_path: /metrics
    static_configs:
      - targets: ["foererkort:9464"]
        labels:
          service: foererkort

  - job_name: "tempo"
    metrics_path: /metrics
    static_configs:
      - targets: ["tempo:3200"]
        labels:
          service: tempo